#!/bin/sh
#Use this to add packages to your machine when running wu_setup_dev
cd /etc/yum.repos.d
wget http://people.centos.org/tru/devtools-1.1/devtools-1.1.repo
yum --enablerepo=testing-1.1-devtools-6 --skip-broken install devtoolset-1.1-gcc devtoolset-1.1-gcc-c++
yum install openldap-devel
curl https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh -o ~/.git-prompt.sh
yum install nano


# Install Python 2.7.6
# install interpreter
cd /code/py
wget http://python.org/ftp/python/2.7.6/Python-2.7.6.tar.xz --no-check-certificate
tar xf Python-2.7.6.tar.xz
cd Python-2.7.6
yum install zlib-devel
yum install openssl-devel
./configure --prefix=/usr/local --enable-unicode=ucs4 --enable-shared LDFLAGS="-Wl,-rpath /usr/local/lib"
make && make altinstall
# install pip (python module management)
wget https://bitbucket.org/pypa/setuptools/raw/bootstrap/ez_setup.py
/usr/local/bin/python2.7 ez_setup.py
easy_install-2.7 pip
# install necessary modules
pip2.7 install requests
pip2.7 install -I progressbar==2.2
pip2.7 install simplemysql
pip2.7 install jenkinsapi
pip2.7 install redis
pip2.7 install dotmap
pip2.7 install numpy
pip2.7 install pymongo
pip2.7 install cluster
pip2.7 install tzlocal
pip2.7 install frozendict
pip2.7 install BeautifulSoup4
pip2.7 install simplemysql
pip2.7 install pycrypto
pip2.7 install python-dateutil
# delete unneeded python installation files
cd /code/py/
rm -rf /code/py/Python-2.7.6
rm -rf /code/py/Python-2.7.6.tar.xz*

# Install C++11
cd /etc/yum.repos.d
wget http://people.centos.org/tru/devtools-1.1/devtools-1.1.repo 
yum --enablerepo=testing-1.1-devtools-6 --skip-broken install devtoolset-1.1-gcc devtoolset-1.1-gcc-c++
